meta_product_name: "Trvlscape"
meta_title: "Trvlscape - Your 3-Day Surprise Trip"
meta_description: "Be curious. Be adventerous. Book a surprise trip with TrvlScape in 5 minutes. Your relax until take-off, TrvlScape takes care of the organization."
meta_image: "../assets/images/og-image.jpg"                       # should exist in `app/assets/images/`   # required for Twitter Cards
