meta_product_name: "convexit|YC|apital"
meta_title: "convexit|YC|apital-investimentos alternativos"
meta_description: "Exponha-se a convexidade: perdas controladas e ganhos ilimitados."
meta_image: "deal.jpg"                       # should exist in `app/assets/images/`   # required for Twitter Cards
